# Generated by Django 3.0.7 on 2020-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_filename', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
